### PR TITLE
Vog 3 Add "JSDT frontend", improve "modern javascript"

### PR DESCRIPTION
**Pull request by psuzzi**
Added new tutorial to build Angular Frontend with Eclipse JSDT.
Improved the content of "modern javascript".

### CODE REVIEW

**Comment by fapdash** [comment]
Looks good, thank you.

**Comment by fapdash** [comment]
Did some minor changes, if you want to check them out: https://github.com/vogellacompany/com.vogella.tutorials.web/commit/601890dce3ecabe580f186d148c4feb529c642ec

**Comment by psuzzi** [comment]
@fap- I see the change is merged (https://github.com/vogellacompany/com.vogella.tutorials.web/blob/master/JavaScript/130_jsdtfrontend.adoc), but I cannot see the article published on the website (http://www.vogella.com/tutorials/JavaScript/article.html#jsfrontend)
Is there something broken or something I missed?

**Comment by fapdash** [comment]
The build was broken, your changes are now live.

**Pull request merged**
